# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games_rounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('user_text', models.CharField(max_length=150)),
                ('giphy_url', models.CharField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='Games_token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_token', models.CharField(max_length=16)),
                ('game_active', models.BooleanField(default='False')),
                ('game_over', models.BooleanField(default='False')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('game_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Games_token')),
            ],
        ),
        migrations.CreateModel(
            name='Users_token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_token', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='user_token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Users_token'),
        ),
        migrations.AddField(
            model_name='games_rounds',
            name='game_token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Games_token'),
        ),
        migrations.AddField(
            model_name='games_rounds',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Users'),
        ),
    ]
