# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=4)),
                ('game_active', models.BooleanField(default='False')),
                ('game_over', models.BooleanField(default='False')),
                ('current_round', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('user_text', models.CharField(max_length=150)),
                ('giphy_url', models.CharField(max_length=2083)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
            ],
        ),
        migrations.RemoveField(
            model_name='gamerounds',
            name='game_token',
        ),
        migrations.RemoveField(
            model_name='gamerounds',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='game_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_token',
        ),
        migrations.DeleteModel(
            name='GameRounds',
        ),
        migrations.DeleteModel(
            name='GameToken',
        ),
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
