# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20160825_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameround',
            name='origin_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='origin_user', to='game.User'),
        ),
        migrations.AddField(
            model_name='gameround',
            name='user',
            field=models.ManyToManyField(related_name='user', to='game.User'),
        ),
        migrations.AlterField(
            model_name='game',
            name='token',
            field=models.CharField(max_length=16),
        ),
    ]
