# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game'),
        ),
    ]
