# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 09:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0003_auto_20160830_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='GifChainNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giphy_url', models.CharField(max_length=2083)),
                ('next_node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='previous_node', to='game.GifChainNode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gif_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GifChainStarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.GifChainNode')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
