# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20160901_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameoverrecords',
            name='game_token',
            field=models.ForeignKey(blank=True, db_column='game_token', default='', on_delete=django.db.models.deletion.CASCADE, to='game.Game', to_field='token'),
        ),
        migrations.AlterField(
            model_name='game',
            name='token',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
