# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20160901_0509'),
        ('game', '0006_auto_20160831_1119'),
    ]

    operations = [
    ]
