# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20160903_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameoverrecords',
            name='game_type',
            field=models.CharField(default='hotseat', max_length=11),
        ),
    ]
