# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 03:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_gameoverrecords_game_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameoverrecords',
            old_name='game_type',
            new_name='mode',
        ),
    ]
