# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 02:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20160904_0348'),
        ('game', '0007_merge_20160903_1123'),
    ]

    operations = [
    ]
