# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_merge_20160905_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gifchainnode',
            name='next_node',
        ),
        migrations.RemoveField(
            model_name='gifchainnode',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gifchainstarter',
            name='first_node',
        ),
        migrations.RemoveField(
            model_name='gifchainstarter',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gifchainstarter',
            name='user',
        ),
        migrations.AddField(
            model_name='game',
            name='total_rounds',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='giphy_url',
            field=models.CharField(blank=True, max_length=2083),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='user_text',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.DeleteModel(
            name='GifChainNode',
        ),
        migrations.DeleteModel(
            name='GifChainStarter',
        ),
    ]
