# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20160905_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='total_rounds',
            field=models.IntegerField(default=4),
        ),
    ]
