# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 17:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20160905_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameround',
            name='origin_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
