# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20160905_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameround',
            name='giphy_url',
            field=models.CharField(max_length=2083),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='user_text',
            field=models.CharField(max_length=150),
        ),
    ]
