# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20160906_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameround',
            name='comitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='giphy_url',
            field=models.CharField(blank=True, max_length=2083),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='user_text',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
