# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20160906_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameround',
            old_name='comitted',
            new_name='committed',
        ),
    ]
